version: "3.9"

services:
  db:
    image: postgres:16
    container_name: bodega_db #La base de datos , nombre del contenedor
    restart: always
    env_file: .env
    ports:
      - "5050:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - inventario_net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadminWeb
    restart: always
    env_file: .env
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - inventario_net

volumes:
  db_data:
 
networks:
  inventario_net:
    driver: bridge